version: '2'
services:
  web:
    image: "miwildfly:7"
    container_name: miwildflycompose
    ports:
     - "8080:8080"
     - "9990:9990"
    links:
     - basedatos:mimariadb
  basedatos:
    image: "mibasedatos:latest"
    container_name: mibasedatoscompose
    ports:
     - "3306:3306"
